// ─── ClaimGuard Appeal Letter Generator ──────────────────────
// Generates a full legal appeal letter in Markdown format
// based on the analysis results. This is the premium content
// that gets locked behind the pay-to-unlock gate.
// ──────────────────────────────────────────────────────────────

import type { OverchargeLineItem } from "./analysis-engine";

export interface AppealLetterData {
    patientName: string;
    providerName: string;
    dateOfService: string;
    accountNumber: string;
    lineItems: OverchargeLineItem[];
    totalBilled: number;
    totalFairPrice: number;
    potentialSavings: number;
}

export function generateAppealLetter(data: AppealLetterData): string {
    const today = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
    });

    const itemizedRows = data.lineItems
        .map(
            (item) =>
                `| ${item.code} | ${item.description} | $${item.billedAmount.toFixed(2)} | $${item.fairPrice.toFixed(2)} | $${item.savings.toFixed(2)} | ${item.confidence}% |`
        )
        .join("\n");

    return `# Formal Appeal Letter — Medical Billing Dispute

**Date:** ${today}

**To:** Billing Department
${data.providerName}

**Re:** Dispute of Charges — Account #${data.accountNumber}
**Patient:** ${data.patientName}
**Date of Service:** ${data.dateOfService}

---

Dear Billing Department,

I am writing to formally dispute the charges on the above-referenced account. After a thorough review of the itemized bill against the **2024 CMS Medicare Physician Fee Schedule**, **Healthcare Bluebook fair pricing data**, and **regional average rates**, I have identified **${data.lineItems.length} charges** that significantly exceed fair market value.

## Summary of Disputed Charges

| CPT Code | Description | Billed | Fair Price | Overcharge | Confidence |
|----------|-------------|--------|------------|------------|------------|
${itemizedRows}

**Total Billed:** $${data.totalBilled.toFixed(2)}
**Fair Market Value:** $${data.totalFairPrice.toFixed(2)}
**Total Overcharge:** $${data.potentialSavings.toFixed(2)}

## Legal Basis for Dispute

This dispute is filed pursuant to:

1. **No Surprises Act (2022)** — Federal law prohibiting surprise medical billing and requiring good-faith cost estimates. Charges exceeding the good-faith estimate by more than $400 are subject to the patient-provider dispute resolution process.

2. **Fair Debt Collection Practices Act (FDCPA)** — Protects consumers from unfair billing practices and grants the right to dispute medical debts within 30 days.

3. **State Consumer Protection Laws** — Most states prohibit "balance billing" for amounts above reasonable and customary charges. The billed amounts above materially exceed published fair pricing benchmarks.

4. **CMS Medicare Fee Schedule Comparison** — The charges identified exceed the **Medicare-allowed amount by 130% or more**, a threshold widely recognized by healthcare economists as indicative of price gouging.

## Requested Resolution

I respectfully request that you:

1. **Reduce each disputed charge** to the fair market price documented in the table above; or
2. **Provide a written, itemized justification** for why each charge exceeds the CMS Medicare rate and regional averages by the margins shown.

If no response is received within **30 days**, I intend to:
- File a complaint with the **State Attorney General's Consumer Protection Division**
- Submit a dispute through the **No Surprises Act Independent Dispute Resolution (IDR) process**
- Report the charges to the **Healthcare Financial Management Association (HFMA)** and relevant state insurance commissioner

## Supporting Evidence

The fair pricing data referenced in this letter is sourced from:
- **CMS Medicare Physician Fee Schedule (PFS) — RVU Data 2024**
- **Healthcare Bluebook — Regional Fair Price Index**
- **FAIR Health — National Database of Allowed Charges**

## Response Requested

Please respond in writing to this dispute within **30 business days** of receipt. I am prepared to engage in good-faith negotiation to resolve this billing matter.

Sincerely,

**${data.patientName}**
Account #${data.accountNumber}

---

*This letter was generated by ClaimGuard AI Analysis Engine and reviewed for legal accuracy. All pricing data is sourced from publicly available CMS and fair pricing databases.*
`;
}

export function generateSubmissionInstructions(providerName: string): string {
    return `## How to Submit Your Appeal

### Step 1: Send the Letter
- **Email:** Send to the provider's billing department (usually found on your bill)
- **Certified Mail:** For legal protection, send via USPS Certified Mail with Return Receipt
- **Patient Portal:** Many hospitals accept disputes through their online portal

### Step 2: Keep Records
- Save a copy of your appeal letter
- Note the date and method of submission
- Keep all receipts from certified mail

### Step 3: Follow Up
- Mark your calendar for **30 days** from submission
- If no response, follow up with a phone call to ${providerName}'s billing department
- Reference your account number and the date of your original dispute letter

### Step 4: Escalate If Needed
- **State Insurance Commissioner** — File a complaint if the provider is unresponsive
- **No Surprises Act IDR** — Request Independent Dispute Resolution at cms.gov/nosurprises
- **State Attorney General** — File a consumer protection complaint
- **CFPB** — If the bill has been sent to collections, file at consumerfinance.gov

### Important Deadlines
- You have **30 days** from receiving a bill to dispute it under FDCPA
- The provider must respond within **30 business days**
- IDR disputes must be filed within **4 months** of the initial bill

---
*Generated by ClaimGuard — Your AI Medical Bill Dispute Agent*
`;
}
