// ─── Multi-Category Appeal Router ────────────────────────────
// Routes to the correct appeal letter generator by category.
// ──────────────────────────────────────────────────────────────

import type { BillCategory, UnifiedAnalysisResult } from "./bill-categories";
import { generateAppealLetter, generateSubmissionInstructions } from "./appeal-generator";

// ─── Auto Insurance: Request for Premium Re-evaluation ──────
function generateAutoAppeal(data: UnifiedAnalysisResult): string {
    const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const rows = data.lineItems
        .map((i) => `| ${i.code} | ${i.description} | $${i.billedAmount.toFixed(2)} | $${i.fairPrice.toFixed(2)} | $${i.savings.toFixed(2)} |`)
        .join("\n");

    return `# Request for Premium Re-evaluation

**Date:** ${today}

**To:** Underwriting Department
${data.providerName || "Auto Insurance Provider"}

**Re:** Request for Premium Re-evaluation — Excessive Rate Increase

---

Dear Underwriting Department,

I am writing to formally request a re-evaluation of my auto insurance premium. After comparing my renewal rates against **NAIC state average data**, **Insurance Information Institute benchmarks**, and **regional competitor pricing**, I have identified **${data.lineItems.length} coverage line(s)** where my premiums significantly exceed fair market rates.

## Premium Comparison

| Coverage | Description | My Premium | State Avg | Excess |
|----------|-------------|------------|-----------|--------|
${rows}

**Total Billed:** $${data.totalBilled.toFixed(2)}
**State Average Total:** $${data.totalFairPrice.toFixed(2)}
**Excess Premium:** $${data.potentialSavings.toFixed(2)}

## Basis for Request

1. **Clean Driving Record** — No claims filed in the past 24+ months and no moving violations on record.
2. **Excellent Credit** — Credit-based insurance scores should qualify me for preferred rates.
3. **State Insurance Commissioner Data** — My premiums exceed published state averages by the margins shown above, which may indicate improper rating factors.
4. **Competitive Market Analysis** — Multiple competitors offer equivalent coverage at rates closer to the state average.

## Requested Action

1. **Re-evaluate my risk profile** using current data and adjust my premium to reflect my clean record.
2. **Provide written justification** for any premium that remains above the state average.
3. **Apply any available discounts** (loyalty, bundling, safe driver, low mileage) that may not have been applied.

If I do not receive a satisfactory response within **14 business days**, I intend to:
- File a rate complaint with the **State Department of Insurance**
- Request a formal review through the **NAIC Consumer Complaint Process**
- Obtain competitive quotes and transfer my policy

Sincerely,

*This letter was generated by ClaimGuard AI — Auto Insurance Analysis Engine*
`;
}

// ─── Rent: Tenant Rights Dispute Letter ─────────────────────
function generateRentAppeal(data: UnifiedAnalysisResult): string {
    const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const rows = data.lineItems
        .map((i) => `| ${i.code} | ${i.description} | $${i.billedAmount.toFixed(2)} | $${i.fairPrice.toFixed(2)} | $${i.savings.toFixed(2)} |`)
        .join("\n");

    return `# Formal Dispute — Rental Charges

**Date:** ${today}

**To:** ${data.providerName || "Property Management"}

**Re:** Dispute of Unauthorized/Illegal Charges

---

Dear Property Management,

I am writing to formally dispute **${data.lineItems.length} charge(s)** on my rental statement that I believe are unauthorized, excessive, or in violation of tenant rights law.

## Disputed Charges

| Code | Issue | Charged | Legal Max | Excess |
|------|-------|---------|-----------|--------|
${rows}

**Total Disputed:** $${data.potentialSavings.toFixed(2)}

## Legal Basis

1. **Tenant Rights Act** — Most states prohibit landlords from charging fees not explicitly agreed upon in the lease, including administrative fees, digital access fees, and insurance surcharges.

2. **Late Fee Limitations** — State law typically caps late fees at **4-5% of monthly rent** and requires a **3-5 day grace period** before late fees can be assessed.

3. **Uniform Residential Landlord and Tenant Act (URLTA)** — Prohibits unconscionable rental terms, including hidden fees not disclosed at lease signing.

4. **Consumer Protection Laws** — Deceptive fee practices may constitute unfair business practices under state consumer protection statutes.

## Requested Resolution

1. **Remove all disputed fees** that are not explicitly authorized in the lease agreement.
2. **Refund any late fees** charged without a proper grace period or exceeding the legal cap.
3. **Provide itemized documentation** for any fee you believe is valid, including the specific lease clause authorizing it.

If unresolved within **30 days**, I will:
- File a complaint with the **State Tenant Rights Agency**
- Report to the **Consumer Financial Protection Bureau (CFPB)**
- Consult with a tenant rights attorney regarding potential violations

Sincerely,

*Generated by ClaimGuard AI — Tenant Rights Analysis Engine*
`;
}

// ─── Utility: Back-Billing Dispute Letter ───────────────────
function generateUtilityAppeal(data: UnifiedAnalysisResult): string {
    const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const rows = data.lineItems
        .map((i) => `| ${i.code} | ${i.description} | $${i.billedAmount.toFixed(2)} | $${i.fairPrice.toFixed(2)} | $${i.savings.toFixed(2)} |`)
        .join("\n");

    return `# Formal Dispute — Utility Billing Errors

**Date:** ${today}

**To:** Billing Department
${data.providerName || "Utility Provider"}

**Re:** Dispute of Back-Billing and Estimated Meter Charges

---

Dear Billing Department,

I am writing to formally dispute **${data.lineItems.length} billing issue(s)** on my account that I believe constitute improper back-billing and/or estimated meter overcharges.

## Disputed Items

| Issue | Description | Billed | Fair Value | Excess |
|-------|-------------|--------|------------|--------|
${rows}

**Total Disputed:** $${data.potentialSavings.toFixed(2)}

## Legal Basis

1. **Back-Billing Regulations** — Most state utility commissions prohibit back-billing customers for more than **12 months** of estimated usage. Any charges beyond this period are the utility's responsibility.

2. **Estimated Meter Reading Standards** — When estimated readings significantly exceed actual usage (as revealed by meter replacement), customers are entitled to a refund of the overcharge.

3. **Public Utility Commission Rules** — Utilities are required to make reasonable efforts to obtain actual meter readings. Extended periods of estimation may constitute a violation of service standards.

4. **Consumer Protection** — Retroactive billing adjustments without customer notification and consent may violate state consumer protection laws.

## Requested Resolution

1. **Remove all back-billing charges** exceeding the 12-month regulatory limit.
2. **Recalculate estimated periods** using actual meter data obtained from the replacement meter.
3. **Provide a full accounting** of estimated vs. actual readings for the disputed periods.
4. **Establish a payment plan** for any legitimate remaining balance.

If unresolved within **30 days**, I will:
- File a formal complaint with the **State Public Utility Commission**
- Request mediation through the **Utility Consumer Advocate's Office**
- Escalate to the **State Attorney General** if the dispute involves unfair billing practices

Sincerely,

*Generated by ClaimGuard AI — Utility Billing Analysis Engine*
`;
}

// ─── Submission Instructions by Category ────────────────────
function generateCategoryInstructions(category: BillCategory, providerName: string): string {
    const shared = `
### Important
- Keep copies of all correspondence
- Note dates and reference numbers
- Follow up if no response within 30 days`;

    switch (category) {
        case "auto":
            return `## How to Submit Your Re-evaluation Request

### Step 1: Send to Underwriting
- **Email** your agent and CC the underwriting department
- **Online Portal** — Most insurers allow rate disputes through your account dashboard
- **Written Letter** via USPS Certified Mail for a paper trail

### Step 2: Escalate If Needed
- **State Dept. of Insurance** — File a rate complaint at your state's DOI website
- **NAIC Consumer Complaint** — naic.org/consumer
- **Switch providers** — Get 3+ competitive quotes to leverage
${shared}

*Generated by ClaimGuard — Auto Insurance Analysis*
`;

        case "rent":
            return `## How to Submit Your Dispute

### Step 1: Send Written Notice
- **Certified Mail** with Return Receipt to ${providerName}
- **Email** with delivery/read receipt if your lease allows electronic communication
- Keep your lease agreement handy for reference

### Step 2: Follow Up
- Your landlord must respond within **14-30 days** depending on your state
- Document any retaliation (illegal in all 50 states)

### Step 3: Escalate If Needed
- **Local Tenant Rights Organization** — Free legal advice
- **State Housing Authority** — File a formal complaint
- **Small Claims Court** — For recovery of illegal fees (no lawyer needed)
- **CFPB** — consumerfinance.gov for housing-related financial disputes
${shared}

*Generated by ClaimGuard — Tenant Rights Analysis*
`;

        case "utility":
            return `## How to Submit Your Dispute

### Step 1: Contact the Utility
- **Call** the billing department and reference your account number
- **Written Dispute** via Certified Mail — creates a regulatory paper trail
- **Online Portal** — Many utilities have formal dispute forms

### Step 2: Request Documentation
- Ask for **all meter readings** (estimated and actual) for the disputed period
- Request the **rate schedule** showing when/why rates changed
- Get a copy of the **back-billing calculation methodology**

### Step 3: Escalate If Needed
- **Public Utility Commission** — File a formal complaint with your state PUC
- **Utility Consumer Advocate** — Free mediation services in most states
- **State Attorney General** — For suspected billing fraud
${shared}

*Generated by ClaimGuard — Utility Billing Analysis*
`;

        default:
            return generateSubmissionInstructions(providerName);
    }
}

// ─── Main Router ────────────────────────────────────────────
export function generateAppealByCategory(
    category: BillCategory,
    data: UnifiedAnalysisResult
): string {
    switch (category) {
        case "medical":
            return generateAppealLetter({
                patientName: "Account Holder",
                providerName: data.providerName || "Healthcare Provider",
                dateOfService: new Date().toLocaleDateString(),
                accountNumber: "See Statement",
                lineItems: data.lineItems,
                totalBilled: data.totalBilled,
                totalFairPrice: data.totalFairPrice,
                potentialSavings: data.potentialSavings,
            });
        case "auto":
            return generateAutoAppeal(data);
        case "rent":
            return generateRentAppeal(data);
        case "utility":
            return generateUtilityAppeal(data);
    }
}

export function generateInstructionsByCategory(
    category: BillCategory,
    providerName: string
): string {
    if (category === "medical") {
        return generateSubmissionInstructions(providerName);
    }
    return generateCategoryInstructions(category, providerName);
}
